site_name: "Apuntes de Seguridad Informática © Antonio Díaz Santamaría"
site_author: Antonio Díaz Santamaría
theme:
  name: 'material'
  palette:
    primary: 'indigo'  # Color primario
    accent: 'red'      # Color de acento
  features:
    - navigation.sections  # Expansión y colapso de las secciones
    - navigation.instant   # Desplazamiento rápido
    - toc.hide             # oculta la barra lateral derecha
    - navigation.top
    - navigation.tabs
      # quita el footer por defecto
extra:
  social: []
  copyright: ""
  generator: false
extra_css:
  - 'assets/css/custom.css'  # Ruta al archivo CSS que acabamos de crear  
  - 'assets/css/stylesheets.css'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
nav:
# --- ESTRUCTURA DE LA UNIDAD 1 (SEGURIDAD PASIVA) ---
  - UD1:
      - "1 Introducción a la seguridad informática": "u01/01-01.md"
      - "2 Tipos de seguridad": "u01/01-02.md"
      - "3 Ubicación y condiciones ambientales": "u01/01-03.md"
      - "4 Protección física de los sistemas": "u01/01-04.md"
      - "5 Sistemas de Alimentación Ininterrumpida (SAI)":
          - "5.1 ¿Qué es un SAI?": "u01/01-05-01.md"
          - "5.2 Riesgos de la red eléctrica": "u01/01-05-02.md"
          - "5.3 Tipos de SAI": "u01/01-05-03.md"
      - "6 Políticas de seguridad lógica pasiva":
          - "6.1 Introducción": "u01/01-06-00.md"
          - "6.2 Las Contraseñas": "u01/01-06-01.md"
          - "6.3 Listas de Control de Acceso": "u01/01-06-02.md"
          - "6.4 ¿Que permite gestionar las ACL?": "u01/01-06-03.md"
      - "7 La importancia del equilibrio en la Seguridad": "u01/01-07.md"
      - "8 Resumen": "u01/01-08.md"
  
  # --- ESTRUCTURA DE LA UNIDAD 2 (DISPOSITIVOS DE ALMACENAMIENTO) ---
  - UD2:
      - "1 Introducción": "u02/02-01.md"
      - "2 Clasificación": "u02/02-02.md"
      - "3 Factores a considerar":
          - "Introducción": "u02/02-03-00.md"
          - "Rendimiento": "u02/02-03-01.md"
          - "Configuraciones":
              - "Fragmentación": "u02/02-03-02-01.md"
              - "Comando TRIM": "u02/02-03-02-02.md"
              - "Temperatura": "u02/02-03-02-03.md"
              - "Otras": "u02/02-03-02-04.md"
          - "Disponibilidad": "u02/02-03-03.md"
          - "Accesibilidad": "u02/02-03-04.md"
      - "4 Tipos de Almacenamiento":
          - "Riesgos en el almacenamiento de datos": "u02/02-04-00.md"
          - "Almacenamiento Redundante": "u02/02-04-01.md"
          - "Almacenamiento Distribuido": "u02/02-04-02.md"
      - "5 Almacenamiento Extraible": "u02/02-05.md"
      - "6 Almacenamiento Remoto": "u02/02-06.md"
      - "7 Virtualización de Servidores": 
          - "Introducción": "u02/02-07-00.md"
          - "Imagen de Respaldo": "u02/02-07-01.md"
          - "Hipervisor": "u02/02-07-02.md"
          - "Copias de Seguridad":
              - "Introducción": "u02/02-07-03-00.md"
              - "Programación de copias": "u02/02-07-03-01.md"
              - "Políticas de copias de seguridad": "u02/02-07-03-02.md"
              - "Restauración": "u02/02-07-03-04.md"
              - "Seguridad física": "u02/02-07-03-05.md"
              - "Buenas Prácticas": "u02/02-07-03-06.md"
      - "8 Documentación Técnica": "u02/02-08.md"
  
  # --- ESTRUCTURA DE LA UNIDAD 3 (SEGURIDAD ACTIVA) ---
  - UD3:
      - "1 Principios de Seguridad Activa": "u03/03-01.md"
      - "2 Mecanismos de Autenticación y Acceso":
          - "2.1 Autenticación (Contraseñas y 2FA)": "u03/03-02-01.md"
          - "2.2 Control de Acceso (ACL)": "u03/03-02-02.md"
          - "2.3 Centralización (Directorios, SSO y Biometría)": "u03/03-02-03.md"
      - "3 Gestión del Software Malicioso (Malware)":
          - "3.1 Software Malicioso (Malware)": "u03/03-03-01.md"
          - "3.2 Software Antimalware": "u03/03-03-02.md"
          - "3.3 Desinfección y Recuperación de Datos": "u03/03-03-03.md"
      - "4 Fortalecimiento del Sistema (Hardening)":
          - "4.1 Hardening y Verificación del Origen": "u03/03-04-01.md"
          - "4.2 Actualizaciones Periódicas": "u03/03-04-02.md"
          - "4.3 Planes de Contingencia y Respuesta": "u03/03-04-03.md"






