site_name: "Apuntes de Seguridad Informática © Antonio Díaz Santamaría"
site_author: Antonio Díaz Santamaría
site_description: "Apuntes del Ciclo Medio de Informática, Sistemas Microinformático y Redes (SMR) - Módulo de Seguridad Informática."
theme:
  name: 'material'
  language: es
  icon:
    logo: material/shield-key # O cualquier otro ícono relevante de Material Icons
  palette:
    primary: 'indigo'  # Color primario
    accent: 'red'      # Color de acento
  features:
    - navigation.sections  # Expansión y colapso de las secciones
    - navigation.instant   # Desplazamiento rápido
    - toc.hide             # oculta la barra lateral derecha
    - navigation.top
    - navigation.tabs      # quita el footer por defecto
extra:
  social: []
  copyright: ""
  generator: false
extra_css:
  - 'assets/css/custom.css'  # Ruta al archivo CSS que acabamos de crear  
  - 'assets/css/stylesheets.css'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search:
      lang: es # Asegura que la búsqueda soporte el español
  
nav:
# --- ESTRUCTURA DE LA UNIDAD 1 (SEGURIDAD PASIVA) ---
  - UD1:
      - "1 Introducción a la seguridad informática": "u01/01-01.md"
      - "2 Tipos de seguridad": "u01/01-02.md"
      - "3 Ubicación y condiciones ambientales": "u01/01-03.md"
      - "4 Protección física de los sistemas": "u01/01-04.md"
      - "5 Sistemas de Alimentación Ininterrumpida (SAI)":
          - "5.1 ¿Qué es un SAI?": "u01/01-05-01.md"
          - "5.2 Riesgos de la red eléctrica": "u01/01-05-02.md"
          - "5.3 Tipos de SAI": "u01/01-05-03.md"
      - "6 Políticas de seguridad lógica pasiva":
          - "6.1 Introducción": "u01/01-06-00.md"
          - "6.2 Las Contraseñas": "u01/01-06-01.md"
          - "6.3 Listas de Control de Acceso": "u01/01-06-02.md"
          - "6.4 ¿Que permite gestionar las ACL?": "u01/01-06-03.md"
      - "7 La importancia del equilibrio en la Seguridad": "u01/01-07.md"
      - "8 Resumen": "u01/01-08.md"
  
  # --- ESTRUCTURA DE LA UNIDAD 2 (DISPOSITIVOS DE ALMACENAMIENTO) ---
  - UD2:
      - "1 Introducción": "u02/02-01.md"
      - "2 Clasificación": "u02/02-02.md"
      - "3 Factores a considerar":
          - "Introducción": "u02/02-03-00.md"
          - "Rendimiento": "u02/02-03-01.md"
          - "Configuraciones":
              - "Fragmentación": "u02/02-03-02-01.md"
              - "Comando TRIM": "u02/02-03-02-02.md"
              - "Temperatura": "u02/02-03-02-03.md"
              - "Otras": "u02/02-03-02-04.md"
          - "Disponibilidad": "u02/02-03-03.md"
          - "Accesibilidad": "u02/02-03-04.md"
      - "4 Tipos de Almacenamiento":
          - "Riesgos en el almacenamiento de datos": "u02/02-04-00.md"
          - "Almacenamiento Redundante": "u02/02-04-01.md"
          - "Almacenamiento Distribuido": "u02/02-04-02.md"
      - "5 Almacenamiento Extraible": "u02/02-05.md"
      - "6 Almacenamiento Remoto": "u02/02-06.md"
      - "7 Virtualización de Servidores": 
          - "Introducción": "u02/02-07-00.md"
          - "Imagen de Respaldo": "u02/02-07-01.md"
          - "Hipervisor": "u02/02-07-02.md"
          - "Copias de Seguridad":
              - "Introducción": "u02/02-07-03-00.md"
              - "Programación de copias": "u02/02-07-03-01.md"
              - "Políticas de copias de seguridad": "u02/02-07-03-02.md"
              - "Restauración": "u02/02-07-03-04.md"
              - "Seguridad física": "u02/02-07-03-05.md"
              - "Buenas Prácticas": "u02/02-07-03-06.md"
      - "8 Documentación Técnica": "u02/02-08.md"
  
  # --- ESTRUCTURA DE LA UNIDAD 3 (SEGURIDAD ACTIVA) ---
  - UD3:
      - "1 Principios de Seguridad Activa": "u03/03-01.md"
      - "2 Objetivos y Ciclo de la Seguridad Activa": "u03/03-02.md"
      - "3 Mecanismos de Autenticación y Acceso":
          - "Autenticación (Contraseñas y 2FA)": "u03/03-03-01.md"
          - "Sistemas Biométricos": "u03/03-03-02.md"
          - "Accesos y Privilegios":
              - "Control de Acceso y Elevación de Privilegios": "u03/03-03-03-01.md"
              - "Tipos de Control de Acceso": "u03/03-03-03-02.md"
              - "Listas de Control de Acceso (ACL)": "u03/03-03-03-03.md"
              - "Funcionamiento de las ACL": "u03/03-03-03-04.md"
              - "Control Centralizado": "u03/03-03-03-05.md"
      - "4 Gestión del Software Malicioso (Malware)":
          - "Software Malicioso (Malware)": "u03/03-04-01.md"
          - "Tipos de Software Malicioso y Medidas de Prevención": "u03/03-04-02.md"
          - "Software Antimalware - Funciones y Detección": "u03/03-04-03.md"
          - "Software Antimalware - Gestión Avanzada y EDR": "u03/03-04-04.md"
          - "Desinfección del Sistema": "u03/03-04-05.md"
          - "Recuperación de Datos": "u03/03-04-06.md"
      - "5 Fortalecimiento del Sistema (Hardening)":
          - "Fortalecimiento del Sistema (Hardening Básico)": "u03/03-05-01.md"
          - "Mantenimiento y Verificación de la Seguridad": "u03/03-05-02.md"
          - "Control, Auditoría y Mejora Continua de la Seguridad": "u03/03-05-03.md"
      - "Glosario": "u03/03-glosario.md"

  # --- ESTRUCTURA DE LA UNIDAD 4 (SEGURIDAD EN LAS TRANSMISIONES) ---
  - UD4:
      - "1 Introducción":
          - "Introducción la privacidad en las comunicaciones": "u04/04-01/01.md"
          - "Riesgos y amenazas en redes locales y públicas": "u04/04-01/02.md"
          - "Relación entre privacidad, integridad, autenticidad y disponibilidad": "u04/04-01/03.md"
          - "Inventariado y control de servicios de red": "u04/04-01/04.md"
          - "Actividades propuestas": "u04/04-01/actividades.md"
      - "2 Criptografía":
          - "¿Que es la criptografía?": "u04/04-02/01.md"
          - "Historia de la criptografía": "u04/04-02/02.md"
          - "Sistemas de cifrado": "u04/04-02/03.md"
          - "Algoritmos de cifrado": "u04/04-02/04.md"
          - "Actividades propuestas": "u04/04-02/actividades.md"
      - "3. Identificación y confianza en las comunicaciones":
          - "Huella digital": "u04/04-03/01.md"
          - "Firma electrónica": "u04/04-03/02.md"
          - "Certificado digital": "u04/04-03/03.md"
          - "Autoridades certificadoras": "u04/04-03/04.md"
          - "Almacenes de certificados": "u04/04-03/05.md"
          - "Infraestructura de clave pública (PKI)": "u04/04-03/06.md"
          - "Buenas prácticas con certificados digitles": "u04/04-03/07.md"
          - "Actividades propuestas": "u04/04-03/actividades.md"
      - "4. Redes cableadas":
          - "Privacidad": "u04/04-04/01.md"
          - "Riesgos": "u04/04-04/02.md"
          - "Control de acceso por dirección MAC": "u04/04-04/03.md"
          - "Separación por subredes": "u04/04-04/04.md"
          - "Rogue DHCP": "u04/04-04/05.md"
          - "VLAN": "u04/04-04/06.md"  
          - "Recomendaciones": "u04/04-04/07.md" 
          - "Actividades propuestas": "u04/04-04/actividades.md"
      - "5. Redes inalámbricas": 
          - "Privacidad": "u04/04-05/01.md"
          - "Vulnerabilidades en redes WiFi": "u04/04-05/02.md"
          - "Protocolos de seguridad WiFi (WEP, WPA, WPA2, WPA3)": "u04/04-05/03.md"
          - "WPS": "u04/04-05-04.md"
          - "Hotspots y redes públicas inalámbricas": "u04/04-05-05.md"
          - "Ataques a redes WiFi": "u04/04-05/06.md"
          - "Buenas prácticas": "u04/04-05/07.md"
          - "Actividades propuestas": "u04/04-05/actividades.md"
      - "6. VPN y Redes Públicas":
          - "¿Por qué una VPN protege?": "u04/04-06/01.md"
          - "Tipos de protocolos VPN": "u04/04-06/02.md"
          - "VPN y cortafuegos": "u04/04-06/03.md"
          - "VPN en Windows": "u04/04-06/04.md"
          - "VPN en Linux": "u04/04-06/05.md"
          - "Cuándo usar VPN": "u04/04-06/06.md"
          - "Actividades propuestas": "u04/04-06/actividades.md"
      - "7. Fraudes e ingeniería social":
          - "Ingeniería social": "u04/04-07/01.md"
          - "Phishing, smishing y vishing": "u04/04-07/02.md"
          - "Ingeniería social en redes locales": "u04/04-07/03.md"
          - "Comportamientos seguros": "u04/04-07/04.md"
          - "Herramientas de protección": "u04/04-07/05.md"
          - "Actividades propuestas": "u04/04-07/actividades.md"
      - "8. Publicidad, rastreadores y spam":
          - "Tracking online": "u04/04-08/01.md"
          - "Publicidad no deseada": "u04/04-08/02.md"
          - "Spam": "u04/04-08/03.md"
          - "Filtrado mediante proxys": "u04/04-08/04.md"
          - "Herramientas antispam": "u04/04-08/05.md"
          - "Navegación privada": "u04/04-08/06.md"
          - "Actividades propuestas": "u04/04-08/actividades.md"
      - "9. Cortafuegos":
          - "Funciones del cortafuegos": "u04/04-09/01.md"
          - "Tipos de cortafuegos": "u04/04-09/02.md"
          - "Firewall de Windows": "u04/04-09/03.md"
          - "Firewall de Linux": "u04/04-09/04.md"
          - "Cortafuegos profesionales": "u04/04-09/05.md"
          - "Cortafuegos en routers": "u04/04-09/06.md"
          - "Buenas prácticas": "u04/04-09/07.md"
          - "Actividades propuestas": "u04/04-09/actividades.md"
      - "10. Proxys":
          - "Qué es un proxy": "u04/04-10/01.md"
          - "Proxy vs cortafuegos": "u04/04-10/02.md"
          - "Proxy como filtrado": "u04/04-10/03.md"
          - "Proxy como privacidad": "u04/04-10/04.md"
          - "Configuración básica": "u04/04-10/05.md"
          - "Proxy contra phishing y spam": "u04/04-10/06.md"
          - "Actividades propuestas": "u04/04-10/actividades.md"
      - "11. Integración de medidas":
          - "Combinación de medidas": "u04/04-11/01.md"
          - "Diseño de una red privada": "u04/04-11/02.md"
          - "Controles técnicos y humanos": "u04/04-11/03.md"
          - "Ejemplo de arquitectura": "u04/04-11/04.md"
          - "Actividades propuestas": "u04/04-11/actividades.md"
     

